services:
  # ---------- INFRAESTRUTURA ----------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    networks:
      - whiteboard-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - whiteboard-network

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
    volumes:
      - vol1:/var/lib/mysql
    networks:
      - whiteboard-network
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - "8080:80"
    networks:
      - whiteboard-network
    restart: unless-stopped

  # ---------- SERVIÇOS BACKEND ----------
  coordinator:
    build:
      context: ./coordinator
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    networks:
      - whiteboard-network

  session-service:
    build:
      context: ./session-service
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    networks:
      - whiteboard-network

  # ---------- FRONTEND ----------
  frontend:
    build:
      context: ./whiteboard-frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - coordinator
      - session-service
    networks:
      - whiteboard-network

# ---------- REDE E VOLUMES ----------
networks:
  whiteboard-network:
    driver: bridge

volumes:
  vol1: