apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: feliperodrigues662/authentication:latest
        ports:
        - containerPort: 4020
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: MARIADB_HOST
          value: haproxy-mariadb
        - name: MARIADB_USER
          value: root
        - name: MARIADB_PASSWORD
          value: admin
        - name: MARIADB_DATABASE
          value: whiteboard_app_db
        - name: JWT_SECRET
          value: segredo123
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  ports:
  - port: 4020
    targetPort: 4020
  selector:
    app: authentication 