apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: feliperodrigues662/coordinator:latest
        ports:
        - containerPort: 4000
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: user
        - name: RABBITMQ_PASSWORD
          value: pass
        - name: JWT_SECRET
          value: segredo123
        - name: CORE_WS_URL
          value: ws://whiteboard-core:4040
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: coordinator 