apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whiteboard-frontend
  template:
    metadata:
      labels:
        app: whiteboard-frontend
    spec:
      containers:
      - name: whiteboard-frontend
        image: feliperodrigues662/whiteboard:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: whiteboard-frontend 