apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whiteboard-frontend
  template:
    metadata:
      labels:
        app: whiteboard-frontend
    spec:
      containers:
      - name: whiteboard-frontend
        image: feliperodrigues662/whiteboard:latest
        ports:
        - containerPort: 80
        env:
        - name: CORE_WS_URL
          value: ws://whiteboard-core:4040
        - name: VITE_URL_AUTH
          value: http://authentication:4020
        - name: VITE_URL_ENDPOINTS
          value: http://session-service:4010
        - name: VITE_URL_SESSION
          value: http://coordinator:4000
        - name: REDIS_HOST
          value: redis   
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: user
        - name: RABBITMQ_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: whiteboard-frontend 