apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
spec:
  serviceName: mariadb-galera
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-galera
  template:
    metadata:
      labels:
        app: mariadb-galera
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb-galera:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: admin
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: whiteboard-cluster
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          value: backup
        - name: MARIADB_REPLICATION_USER
          value: repl
        - name: MARIADB_REPLICATION_PASSWORD
          value: replpass
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4568
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mariadb-galera 