apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: feliperodrigues662/session-service:latest
        ports:
        - containerPort: 4010
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: MARIADB_HOST
          value: haproxy-mariadb
        - name: MARIADB_USER
          value: root
        - name: MARIADB_PASSWORD
          value: admin
        - name: MARIADB_DATABASE
          value: whiteboard_app_db
        - name: JWT_SECRET
          value: segredo123
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  type: LoadBalancer
  ports:
  - port: 4010
    targetPort: 4010
  selector:
    app: session-service 